name: Test
on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  test:
    name: Test and deploy health check
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout code
        uses: actions/checkout@v3

      - name: Setup | Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build | Test
        working-directory: ./src
        run: cargo test --release      

      - name: Build | Build
        working-directory: ./src
        run: cargo build --release      

